### ISSUE TITLE
Credit card with vertical number format only recognizes 4 digits

### ISSUE THREAD

**Issue by omartinma** [blinkcard/blinkcard-flutter#18]
Hello,

According to this [blog post](https://microblink.com/resources/blog/blinkcard-scans-vertical-payment-cards/) reading vertical cards should be supported but when trying so with multiple cards I only receive the first 4 digits of the card. Is there any special recognizer or step for these cards?

Thanks!

**Comment by MBrizic01** [comment]
Hi @omartinma, yes we support the vertical cards, too. The card number on those cards may be invalid. Could you check if the card number on these cards is valid, and allow the [setting](https://github.com/blinkcard/blinkcard-ios/blob/4c49da9663cb2ad731662528681b663f8a0a4e27/CHANGELOG.md?plain=1#L13) `allowInvalidCardNumber`, or that you didn't [anonymze](https://github.com/blinkcard/blinkcard-ios/blob/4c49da9663cb2ad731662528681b663f8a0a4e27/BlinkCard.xcframework/ios-arm64/BlinkCard.framework/Headers/MBBlinkCardAnonymizationSettings.h#L29) the card number prefix?  
If you are still facing issues, feel free to reach out to support@microblink.com and we will analyze the cards and assist you

**Comment by omartinma** [comment]
@MBrizic01 i just tried with allowInvalidCardNumber and still I'm getting only 4 digits. I tried as example the one you have in the blog post and it only returns "4003"
![image](https://github.com/user-attachments/assets/8258fb5c-ffa9-4d2d-82cd-83fba9a4f924)

**Comment by MBrizic01** [comment]
@omartinma I tested the same card and was able to obtain the full card number in the results. The only difference is that the card number will be displayed in multiple lines because this is how it is written on the card.
e.g. 
4003
9136
6406 etc
Is it possible that you are displaying only one line? I tested this with the sample app from our latest release, and it works as expected.
