### ISSUE TITLE
Flip card disable option not exists

### ISSUE THREAD

**Issue by nadas00** [blinkcard/blinkcard-flutter#8]
I only want to scan front side of card but it forces me to flip card sometimes.    

I set  _cardRecognizer.extractCvv = false; but nothing changed. How can I disable flipping card.

**Comment by anjapenic** [comment]
Hello @nadas00,

Since the BlinkCard is a recognizer based on machine learning, it will search for the info you want to get from a card until it extracts it. That is, if it doesn't find the wanted info on the front side, it will ask you to scan the back side.

This is highly dependable on how the actual card is organized - for example, if the card you want to scan has CVV and IBAN on the back, you can set
```
blinkCard.setExtractCvv(false);
blinkCard.setExtractIban(false);
```
and it will scan only the front.

However, there are cards that have info such as expiry date on the back and in that case, it will ask you to scan the back side as well since it didn't find the wanted info on the front.

So, it is not actually possible to set the SDK to scan only the front of the card, unless you know the exact format of the cards you will scan and are sure that the info you want to extract will always be on the front of the card. In that case, you can disable scanning of the info you expect to find on the back and it will scan only the front.

Hope this helps, if any additional info is required please let us know.

Best regards,
Anja

**Comment by nadas00** [comment]
@anjapenic Thank you for great explanation. It helped.
